# Generated by Django 2.1.7 on 2019-03-19 01:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50, verbose_name='Author twitter ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author twitter profile full name')),
                ('handle', models.CharField(max_length=50, verbose_name='Author twitter profile handle')),
                ('description', models.TextField(verbose_name='Author twitter profile description')),
                ('created_at', models.DateTimeField(verbose_name='Author twitter profile creation datetime')),
                ('profile_image', models.URLField(verbose_name='Author twitter profile image')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, verbose_name='Tweet ID')),
                ('text', models.TextField(verbose_name='Tweet text')),
                ('created_at', models.DateTimeField(verbose_name='Tweet creation datetime')),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='content.Author', verbose_name='Tweet author')),
            ],
        ),
    ]
